// i18n PT/EN — portado do design (app-i18n-strings.jsx + core).
export type Lang = "pt" | "en";

type Entry = {
  pt: string | string[] | ((...a: never[]) => string | string[]);
  en: string | string[] | ((...a: never[]) => string | string[]);
};

export const STRINGS: Record<string, Entry> = {
  // Tab bar
  "tab.home": { pt: "Início", en: "Home" },
  "tab.card": { pt: "Pontos", en: "Points" },
  "tab.reservations": { pt: "Reservas", en: "Bookings" },
  "tab.menu": { pt: "Menu", en: "Menu" },
  "tab.profile": { pt: "Perfil", en: "Profile" },

  // Landing
  "land.badge": { pt: "CAFÉ & SNACK-BAR", en: "CAFÉ & SNACK-BAR" },
  "land.title": { pt: ["O teu cantinho", "no bairro"], en: ["Your little corner", "of the neighbourhood"] },
  "land.sub": { pt: "Bons cafés, melhores conversas e aquele sabor de casa.", en: "Good coffee, better conversations and that taste of home." },
  "land.register": { pt: "Criar conta grátis", en: "Create free account" },
  "land.member": { pt: "Já sou membro", en: "I'm already a member" },
  "land.memberQ": { pt: "Já tens conta?", en: "Already have an account?" },
  "land.memberLink": { pt: "Entrar", en: "Log in" },
  "land.why": { pt: "Porquê ser membro", en: "Why become a member" },
  "land.f1.t": { pt: "Ganha pontos", en: "Earn points" },
  "land.f1.d": { pt: "Em cada visita acumulas pontos e carimbos.", en: "Earn points and stamps on every visit." },
  "land.f2.t": { pt: "Troca recompensas", en: "Redeem rewards" },
  "land.f2.d": { pt: "Cafés, bolos e descontos só para membros.", en: "Coffees, cakes and members-only discounts." },
  "land.f3.t": { pt: "Reserva mesa", en: "Book a table" },
  "land.f3.d": { pt: "Garante o teu lugar em poucos toques.", en: "Secure your spot in just a few taps." },
  "land.house": { pt: "Da nossa casa", en: "From our kitchen" },
  "land.hours": { pt: "Horário", en: "Hours" },
  "land.hoursVal": { pt: ["Seg–Sex · 06h30–17h00", "Sáb e Dom · 07h00–15h00"], en: ["Mon–Fri · 6:30am–5pm", "Sat & Sun · 7am–3pm"] },
  "land.where": { pt: "Onde", en: "Where" },
  "land.whereVal": { pt: ["R. Dâmaso da Encarnação 53C", "8700-249 Quelfes · Olhão"], en: ["R. Dâmaso da Encarnação 53C", "8700-249 Quelfes · Olhão"] },
  "land.phone": { pt: "Telefone", en: "Phone" },
  "land.phoneVal": { pt: "289 034 275", en: "289 034 275" },
  "land.address": { pt: "Morada", en: "Address" },
  "land.footer": { pt: "Feito com carinho para o Bairro · Fornecido por RedDune Solutions", en: "Made with love for the neighbourhood · Powered by RedDune Solutions" },
  "land.visit": { pt: "Visita-nos", en: "Visit us" },
  "land.openMaps": { pt: "Ver no Google Maps", en: "Open in Google Maps" },

  // Auth
  "auth.regTitle": { pt: "Criar conta", en: "Create account" },
  "auth.loginTitle": { pt: "Bem-vinda de volta", en: "Welcome back" },
  "auth.regSub": { pt: "Junta-te aos Amigos do Bairro", en: "Join the Amigos do Bairro" },
  "auth.loginSub": { pt: "Entra para ver os teus pontos", en: "Sign in to see your points" },
  "auth.tabLogin": { pt: "Entrar", en: "Sign in" },
  "auth.tabReg": { pt: "Registar", en: "Register" },
  "auth.name": { pt: "Nome", en: "Name" },
  "auth.namePh": { pt: "O teu nome", en: "Your name" },
  "auth.email": { pt: "Email", en: "Email" },
  "auth.pass": { pt: "Palavra-passe", en: "Password" },
  "auth.phone": { pt: "Telemóvel", en: "Phone" },
  "auth.forgot": { pt: "Esqueci-me?", en: "Forgot password?" },
  "auth.remember": { pt: "Manter sessão", en: "Stay signed in" },
  "auth.regBtn": { pt: "Criar conta", en: "Create account" },
  "auth.loginBtn": { pt: "Entrar na conta", en: "Sign in" },
  "auth.regLoading": { pt: "A criar conta", en: "Creating account" },
  "auth.loginLoading": { pt: "A entrar", en: "Signing in" },
  "auth.terms": { pt: "Ao registar aceitas os termos e a política de privacidade dos Amigos do Bairro.", en: "By registering you accept the Amigos do Bairro terms and privacy policy." },
  "auth.checkEmailTitle": { pt: "Conta criada! 🎉", en: "Account created! 🎉" },
  "auth.checkEmailSub": { pt: "Enviámos-te um email para confirmares a tua conta. Abre-o e clica no link antes de entrares.", en: "We've sent you an email to confirm your account. Open it and click the link before signing in." },
  "auth.backToLogin": { pt: "Voltar a entrar", en: "Back to sign in" },
  "auth.resentTitle": { pt: "Confirma o teu email ✉️", en: "Confirm your email ✉️" },
  "auth.resentSub": { pt: "Já tinhas começado o registo com este email mas ainda não o confirmaste. Reenviámos-te o link — abre o email e clica para ativares a conta.", en: "You'd already started signing up with this email but hadn't confirmed it yet. We've resent the link — open the email and click it to activate your account." },
  "auth.alreadyExists": { pt: "Já existe uma conta com este email. Entra com a tua palavra-passe.", en: "An account with this email already exists. Sign in with your password." },

  // Comum / QR
  "common.lang": { pt: "Idioma", en: "Language" },
  "common.close": { pt: "Fechar", en: "Close" },
  "qr.title": { pt: "O teu cartão", en: "Your card" },
  "qr.sub": { pt: "Mostra ao balcão para somar pontos", en: "Show at the counter to earn points" },
  "qr.codeLabel": { pt: "Ou diz este código", en: "Or read out this code" },

  // Home / MemberCard
  "mc.balance": { pt: "Saldo de pontos", en: "Points balance" },
  "mc.since": { pt: (d: string) => `Membro desde ${d}`, en: (d: string) => `Member since ${d}` },
  "mc.show": { pt: "Mostrar", en: "Show" },
  "home.greet": { pt: "Bom dia,", en: "Good morning," },
  "home.hello": { pt: (n: string) => `Olá, ${n} 👋`, en: (n: string) => `Hi, ${n} 👋` },
  "home.stampCard": { pt: "Cartão de carimbos", en: "Stamp card" },
  "home.q.reserve": { pt: "Reservar", en: "Book" },
  "home.q.menu": { pt: "Ver menu", en: "View menu" },
  "home.q.prizes": { pt: "Prémios", en: "Prizes" },
  "home.q.card": { pt: "Cartão", en: "Card" },
  "home.toGoPre": { pt: "Faltam ", en: "Just " },
  "home.almost": { pt: "Estás quase lá!", en: "You're almost there!" },
  "home.toReward": { pt: (n: number, nome: string) => `Faltam ${n} pts para "${nome}".`, en: (n: number, nome: string) => `${n} pts to go for "${nome}".` },
  "home.canRedeem": { pt: "Já podes resgatar! 🎉", en: "You can redeem now! 🎉" },
  "home.redeemAndNext": { pt: (n: number, nome: string) => `Resgata já · faltam ${n} pts para "${nome}".`, en: (n: number, nome: string) => `Redeem now · ${n} pts to go for "${nome}".` },
  "home.allUnlockedSub": { pt: "Tens pontos para qualquer recompensa. Vê o catálogo.", en: "You have enough for any reward. See the catalogue." },
  "home.prizes": { pt: "Os teus prémios", en: "Your rewards" },
  "home.prizesSub": { pt: "Vê o que podes trocar pelos teus pontos.", en: "See what you can redeem with your points." },
  "home.news": { pt: "Novidades no bairro", en: "Neighbourhood news" },
  "tiers.title": { pt: "Escalões do clube", en: "Club tiers" },
  "tiers.sub": { pt: "Acumula pontos e sobe de escalão para desbloquear mais benefícios.", en: "Earn points and climb the tiers to unlock more perks." },
  "tiers.current": { pt: "Atual", en: "Current" },
  "tiers.from": { pt: (n: number) => `A partir de ${n} pts`, en: (n: number) => `From ${n} pts` },
  "tiers.toNext": { pt: (n: number, t: string) => `Faltam ${n} pts para ${t}`, en: (n: number, t: string) => `${n} pts to reach ${t}` },
  "home.n1.t": { pt: "Pastéis de nata 2x1", en: "Custard tarts 2-for-1" },
  "home.n1.d": { pt: "Todas as quartas, das 16h às 18h.", en: "Every Wednesday, 4pm to 6pm." },
  "home.n2.t": { pt: "Novo Prato do Dia", en: "New Dish of the Day" },
  "home.n2.d": { pt: "Bacalhau à Brás esta semana.", en: "Bacalhau à Brás this week." },

  // LoyaltyCard
  "card.title": { pt: "O meu cartão", en: "My card" },
  "card.pointsCap": { pt: "pontos · 1€ = 10pt", en: "points · €1 = 10pt" },
  "card.stampsCap": { pt: "carimbos · 10 = raspadinhas", en: "stamps · 10 = scratch cards" },
  "card.yourStamps": { pt: "Os teus carimbos", en: "Your stamps" },
  "card.perStamp": { pt: "compra ≥15€ = 1 carimbo", en: "purchase ≥€15 = 1 stamp" },
  "card.stampRule": { pt: "Cada compra ≥15€ vale 1 carimbo · máx 2 por semana", en: "Each purchase ≥€15 earns 1 stamp · max 2 per week" },
  "card.register": { pt: "Registar compra", en: "Log a purchase" },
  "card.registerDemo": { pt: "(demo balcão)", en: "(counter demo)" },
  "card.haveScratch": { pt: (n: number) => `Tens ${n} raspadinha${n > 1 ? "s" : ""}!`, en: (n: number) => `You have ${n} scratch card${n > 1 ? "s" : ""}!` },
  "card.yourScratch": { pt: "As tuas raspadinhas", en: "Your scratch cards" },
  "card.openReveal": { pt: "Abre e descobre o prémio", en: "Open and reveal your prize" },
  "card.collect10": { pt: "Junta 10 carimbos para ganhar", en: "Collect 10 stamps to earn one" },
  "card.history": { pt: "Histórico de pontos", en: "Points history" },
  "card.nextStamp": { pt: "Próximo carimbo", en: "Next stamp" },
  "card.expiring": { pt: (p: number, d: number) => `${p} pontos expiram em ${d} dia${d === 1 ? "" : "s"}. Usa-os antes!`, en: (p: number, d: number) => `${p} points expire in ${d} day${d === 1 ? "" : "s"}. Use them soon!` },
  "sheet.register": { pt: "Registar compra", en: "Log a purchase" },
  "sheet.registerSub": { pt: (e: number) => `O balcão regista o valor gasto. A cada ${e}€ soma 1 carimbo.`, en: (e: number) => `The counter logs the amount spent. Every €${e} adds 1 stamp.` },

  // Rewards (rew.swap/rew.need usados no PrizesScreen)
  "rew.swap": { pt: "Trocar", en: "Redeem" },
  "rew.need": { pt: "Faltam", en: "Not yet" },

  // Reservas
  "res.title": { pt: "Reservar mesa", en: "Book a table" },
  "res.titleShort": { pt: "Reserva", en: "Booking" },
  "res.booked": { pt: "Mesa reservada!", en: "Table booked!" },
  "res.bookedSub": { pt: "Esperamos por ti no bairro. Enviámos a confirmação por email.", en: "See you in the neighbourhood. We've emailed your confirmation." },
  "res.requested": { pt: "Pedido enviado!", en: "Request sent!" },
  "res.requestedSub": { pt: "A tua mesa fica em pedido. Avisamos-te aqui e no telemóvel assim que o café confirmar.", en: "Your table is pending. We'll let you know here and on your phone as soon as the café confirms." },
  "res.status": { pt: "Estado", en: "Status" },
  "res.statusPending": { pt: "À espera de confirmação", en: "Awaiting confirmation" },
  "res.statusPendingShort": { pt: "Pendente", en: "Pending" },
  "res.statusUnavailable": { pt: "Não disponível", en: "Unavailable" },
  "res.request": { pt: (wd: string, t: string) => `Pedir · ${wd} ${t}`, en: (wd: string, t: string) => `Request · ${wd} ${t}` },
  "res.noSlots": { pt: "Sem horários disponíveis neste dia.", en: "No times available on this day." },
  "res.hoursNote": { pt: "Horários dentro do funcionamento do café.", en: "Times within the café's opening hours." },
  "res.leadNote": { pt: "As reservas são feitas com pelo menos 12 h de antecedência.", en: "Reservations require at least 12 hours' notice." },
  "res.leadError": { pt: "As reservas têm de ser feitas com pelo menos 12 horas de antecedência.", en: "Reservations must be made at least 12 hours in advance." },
  "res.between": { pt: (a: string, b: string) => `Entre ${a} e ${b}`, en: (a: string, b: string) => `Between ${a} and ${b}` },
  "res.outOfRange": { pt: (a: string, b: string) => `Escolhe uma hora entre ${a} e ${b}.`, en: (a: string, b: string) => `Pick a time between ${a} and ${b}.` },
  "res.archive": { pt: "Arquivar", en: "Archive" },
  "res.cancelNote": { pt: "Para cancelar, liga ao café:", en: "To cancel, call the café:" },
  "res.noShowWarn": { pt: "Se reservares e não compareceres, o café pode bloquear as reservas desta conta.", en: "If you book and don't show up, the café may block reservations for this account." },
  "res.blockedTitle": { pt: "Reservas bloqueadas", en: "Reservations blocked" },
  "res.blockedSub": { pt: "O café bloqueou as reservas desta conta. Fala connosco no café para resolver.", en: "The café has blocked reservations for this account. Talk to us at the café to sort it out." },
  "res.day": { pt: "Dia", en: "Day" },
  "res.hour": { pt: "Hora", en: "Time" },
  "res.people": { pt: "Pessoas", en: "People" },
  "res.person1": { pt: "pessoa", en: "person" },
  "res.personN": { pt: "pessoas", en: "people" },
  "res.newRes": { pt: "Nova reserva", en: "New booking" },
  "res.next": { pt: "Próxima reserva", en: "Next booking" },
  "res.mine": { pt: "Os teus pedidos", en: "Your requests" },
  "res.newReq": { pt: "Novo pedido de reserva", en: "New booking request" },
  "res.chooseDay": { pt: "Escolhe o dia", en: "Choose the day" },
  "res.chooseTime": { pt: "A que horas", en: "What time" },
  "res.chooseHowMany": { pt: "Quantas pessoas", en: "How many people" },
  "res.upTo12": { pt: "Mesas até 12 lugares", en: "Tables up to 12 seats" },
  "res.confirm": { pt: (wd: string, t: string) => `Confirmar · ${wd} ${t}`, en: (wd: string, t: string) => `Confirm · ${wd} ${t}` },
  "res.pickHour": { pt: "Escolhe uma hora", en: "Pick a time" },
  "res.statusConfirmed": { pt: "Confirmada", en: "Confirmed" },
  "res.today": { pt: "Hoje", en: "Today" },
  "res.tomorrow": { pt: "Amanhã", en: "Tomorrow" },

  // Splash / loading
  "splash.tag": { pt: "CAFÉ & SNACK-BAR", en: "CAFÉ & SNACK-BAR" },
  "splash.load": { pt: "A preparar o teu balcão…", en: "Warming up your counter…" },

  // Notificações no telemóvel (card no perfil)
  "push.title": { pt: "Notificações no telemóvel", en: "Phone notifications" },
  "push.descOn": { pt: "Ativas — recebes novidades e ofertas.", en: "On — you'll get news and offers." },
  "push.descOff": { pt: "Recebe novidades e ofertas do café.", en: "Get news and offers from the café." },
  "push.descDenied": { pt: "Bloqueadas no browser. Ativa nas definições do site.", en: "Blocked in the browser. Enable them in the site settings." },
  "push.enable": { pt: "Ativar", en: "Enable" },
  "push.disable": { pt: "Desligar", en: "Turn off" },
  "push.err": { pt: "Não foi possível ativar neste dispositivo.", en: "Couldn't enable on this device." },
  "mail.title": { pt: "Emails do café", en: "Café emails" },
  "mail.descOn": { pt: "Ativos — recebes reservas, ofertas e novidades também por email.", en: "On — you'll also get bookings, gifts and news by email." },
  "mail.descOff": { pt: "Recebe reservas, ofertas e novidades por email.", en: "Get bookings, gifts and news by email." },
  "mail.err": { pt: "Não foi possível guardar. Tenta novamente.", en: "Couldn't save. Try again." },

  // Instalar a app (PWA) — card no perfil
  "install.title": { pt: "Instalar a app", en: "Install the app" },
  "install.desc": { pt: "Adiciona ao ecrã principal para abrir num toque e receber notificações.", en: "Add it to your home screen for one-tap access and notifications." },
  "install.btn": { pt: "Instalar", en: "Install" },
  "install.installed": { pt: "App instalada ✓", en: "App installed ✓" },
  "install.iosTitle": { pt: "Como instalar no iPhone", en: "How to install on iPhone" },
  "install.iosStep1": { pt: ["Toca em ", "Partilhar", " na barra do Safari."], en: ["Tap ", "Share", " in the Safari bar."] },
  "install.iosStep2": { pt: ["Escolhe ", "Adicionar ao ecrã principal", "."], en: ["Choose ", "Add to Home Screen", "."] },
  "install.androidHint": { pt: "No menu do browser (⋮), escolhe \"Instalar app\" ou \"Adicionar ao ecrã principal\".", en: "In the browser menu (⋮), choose \"Install app\" or \"Add to Home Screen\"." },

  // Menu
  "menu.title": { pt: "Menu", en: "Menu" },
  "menu.pointNote": { pt: ["Cada euro gasto vale ", "10 pontos", " no teu cartão."], en: ["Every euro spent is worth ", "10 points", " on your card."] },

  // Perfil
  "prof.title": { pt: "Perfil", en: "Profile" },
  "prof.stat.points": { pt: "pontos", en: "points" },
  "prof.stat.stamps": { pt: "carimbos", en: "stamps" },
  "prof.stat.visits": { pt: "visitas", en: "visits" },
  "prof.r.edit": { pt: "Editar perfil", en: "Edit profile" },
  "prof.r.notif": { pt: "Notificações", en: "Notifications" },
  "prof.r.notifOn": { pt: "Ativas", en: "On" },
  "prof.r.faq": { pt: "Perguntas frequentes", en: "FAQ" },
  "prof.admin": { pt: "Painel de administração", en: "Admin panel" },

  // FAQ
  "faq.title": { pt: "Perguntas frequentes", en: "FAQ" },
  "faq.s.points": { pt: "Sistema de pontos", en: "Points system" },
  "faq.s.stamps": { pt: "Sistema de carimbos", en: "Stamp system" },
  "faq.p1.q": { pt: "Como funcionam os meus pontos?", en: "How do my points work?" },
  "faq.p1.a": { pt: "Cada compra ou interação gera pontos. Cada 1€ gasto vale 10 pontos. Ganhas ainda 150 pontos ao registares-te e 10 pontos ao fazer check-in no café.", en: "Every purchase or interaction earns points. Each €1 spent is worth 10 points. You also get 150 points when you sign up and 10 points for checking in at the café." },
  "faq.p2.q": { pt: "Os meus pontos expiram?", en: "Do my points expire?" },
  "faq.p2.a": { pt: "Sim. Cada lote de pontos é válido durante 180 dias (6 meses) a contar do momento em que o acumulaste.", en: "Yes. Each batch of points is valid for 180 days (6 months) from the moment you earned it." },
  "faq.p3.q": { pt: "Por que ordem são descontados os pontos?", en: "In what order are points spent?" },
  "faq.p3.a": { pt: "Usamos sempre primeiro os teus pontos mais antigos — os que estão mais perto de expirar — protegendo o resto do teu saldo, enquanto os pontos novos mantêm a sua validade.", en: "We always use your oldest points first — the ones closest to expiring — protecting the rest of your balance, while newer points keep their validity." },
  "faq.c1.q": { pt: "Como ganho carimbos?", en: "How do I earn stamps?" },
  "faq.c1.a": { pt: "Cada compra de valor igual ou superior a 15€ numa única transação vale 1 carimbo. Há um limite de 2 carimbos por semana.", en: "Each purchase of €15 or more in a single transaction earns 1 stamp. There's a limit of 2 stamps per week." },
  "faq.c2.q": { pt: "O que acontece ao completar o cartão?", en: "What happens when I complete the card?" },
  "faq.c2.a": { pt: "Ao atingir os 10 carimbos, o cartão reinicia e recebes de imediato duas raspadinhas: uma de prémios regulares e uma de grandes prémios.", en: "When you reach 10 stamps, the card resets and you immediately get two scratch cards: one for regular prizes and one for big prizes." },
  "prof.adminSub": { pt: "Gerir prémios, resgates e estatísticas", en: "Manage prizes, redemptions and stats" },
  "prof.logout": { pt: "Terminar sessão", en: "Log out" },

  // Editar perfil
  "edit.title": { pt: "Editar perfil", en: "Edit profile" },
  "edit.photo": { pt: "Alterar foto", en: "Change photo" },
  "edit.section": { pt: "Dados pessoais", en: "Personal details" },
  "edit.name": { pt: "Nome completo", en: "Full name" },
  "edit.namePh": { pt: "O teu nome", en: "Your name" },
  "edit.email": { pt: "Email", en: "Email" },
  "edit.phone": { pt: "Telemóvel", en: "Phone" },
  "edit.birthday": { pt: "Data de nascimento", en: "Date of birth" },
  "edit.member": { pt: "Membro desde", en: "Member since" },
  "edit.save": { pt: "Guardar alterações", en: "Save changes" },
  "edit.saved": { pt: "Perfil atualizado ✓", en: "Profile updated ✓" },

  // Raspadinhas / Prémios
  "sc.special": { pt: "ESPECIAL", en: "SPECIAL" },
  "sc.common": { pt: "COMUM", en: "COMMON" },
  "sc.scratchHere": { pt: "✦  RASPA AQUI  ✦", en: "✦  SCRATCH HERE  ✦" },
  "sc.dragReveal": { pt: "arrasta o dedo para revelar", en: "drag your finger to reveal" },
  "sc.cardLabel": { pt: "RASPADINHA", en: "SCRATCH CARD" },
  "sc.won": { pt: "🎉 Ganhaste!", en: "🎉 You won!" },
  "sc.wonSub": { pt: "Guarda na carteira e mostra ao balcão para usar.", en: "Save it to your wallet and show it at the counter to use." },
  "sc.saveWallet": { pt: "Guardar na carteira", en: "Save to wallet" },
  "sc.hintRaspar": { pt: "Raspa para descobrir o prémio.", en: "Scratch to reveal your prize." },
  "sc.revealing": { pt: "A revelar…", en: "Revealing…" },
  "sc.openError": { pt: "Não foi possível abrir. Fecha e tenta de novo.", en: "Couldn't open it. Close and try again." },
  "sc.noPrize": { pt: "Sem sorte desta vez 😊", en: "No luck this time 😊" },
  "sc.noPrizeSub": { pt: "Continua a juntar carimbos — a próxima raspadinha pode ser a tua!", en: "Keep collecting stamps — your next scratch card could be the one!" },
  "pz.title": { pt: "Prémios", en: "Prizes" },
  "pz.bigPrize": { pt: "Prémio grande", en: "Big prize" },
  "pz.houseTreat": { pt: "Mimo da casa", en: "House treat" },
  "pz.scratch": { pt: "Raspar", en: "Scratch" },
  "pz.yourScratch": { pt: "AS TUAS RASPADINHAS", en: "YOUR SCRATCH CARDS" },
  "pz.havePending": { pt: (n: number) => `Tens ${n} raspadinha${n > 1 ? "s" : ""} por abrir!`, en: (n: number) => `You have ${n} scratch card${n > 1 ? "s" : ""} to open!` },
  "pz.noneYet": { pt: "Ainda sem raspadinhas", en: "No scratch cards yet" },
  "pz.eachTen": { pt: "A cada 10 carimbos ganhas 1 especial + 1 comum.", en: "Every 10 stamps earns you 1 special + 1 common." },
  "pz.toNext": { pt: (n: number) => `Faltam ${n} carimbo${n > 1 ? "s" : ""} para 2 raspadinhas.`, en: (n: number) => `${n} more stamp${n > 1 ? "s" : ""} for 2 scratch cards.` },
  "pz.keepGoing": { pt: "Continua a juntar carimbos — a tua sorte está quase a chegar.", en: "Keep collecting stamps — your luck is almost here." },
  "pz.myWallet": { pt: "A minha carteira", en: "My wallet" },
  "pz.code": { pt: "Código", en: "Code" },
  "pz.used": { pt: "Usado", en: "Used" },
  "pz.toUse": { pt: "Por usar", en: "To use" },
  "pz.walletEmpty": { pt: "Os prémios que ganhares aparecem aqui.", en: "Prizes you win will appear here." },
  "pz.walletActive": { pt: "Carteira", en: "Wallet" },
  "pz.walletArchive": { pt: "Arquivo", en: "Archive" },
  "pz.walletNoUsed": { pt: "Ainda não usaste nenhum prémio.", en: "You haven't used any prizes yet." },
  "pz.swapPoints": { pt: "Trocar pontos por mimos", en: "Swap points for treats" },

  // Celebração
  "win.full": { pt: "Cartola completa! 🎉", en: "Card complete! 🎉" },
  "win.open": { pt: "Abrir raspadinhas", en: "Open scratch cards" },

  // Toasts
  "toast.redeem": { pt: (n: string) => `Resgataste: ${n} 🎉`, en: (n: string) => `Redeemed: ${n} 🎉` },
  "toast.stamps": { pt: (a: number, n: number) => `+${a}€ · ${n} carimbo${n > 1 ? "s" : ""} ✓`, en: (a: number, n: number) => `+€${a} · ${n} stamp${n > 1 ? "s" : ""} ✓` },
  "toast.spend": { pt: (a: number) => `+${a}€ registados`, en: (a: number) => `+€${a} recorded` },
  "toast.prizeSaved": { pt: "Prémio guardado na carteira ✓", en: "Prize saved to wallet ✓" },
  "toast.redeemOk": { pt: "Resgate validado ✓", en: "Redemption validated ✓" },
  "toast.bookingOk": { pt: "Pedido de reserva enviado ✓", en: "Booking request sent ✓" },
};
