// i18n PT/EN — portado do design (app-i18n-strings.jsx + core).
export type Lang = "pt" | "en";

type Entry = {
  pt: string | string[] | ((...a: never[]) => string | string[]);
  en: string | string[] | ((...a: never[]) => string | string[]);
};

export const STRINGS: Record<string, Entry> = {
  // Tab bar
  "tab.home": { pt: "Início", en: "Home" },
  "tab.card": { pt: "Pontos", en: "Points" },
  "tab.reservations": { pt: "Reservas", en: "Bookings" },
  "tab.menu": { pt: "Menu", en: "Menu" },
  "tab.profile": { pt: "Perfil", en: "Profile" },

  // Landing
  "land.badge": { pt: "CAFÉ & SNACK-BAR DO BAIRRO", en: "NEIGHBOURHOOD CAFÉ & SNACK-BAR" },
  "land.title": { pt: ["O teu cantinho", "no bairro"], en: ["Your little corner", "of the neighbourhood"] },
  "land.sub": { pt: "Junta-te ao clube dos Amigos do Bairro. Cada café conta — acumula pontos, troca recompensas e reserva a tua mesa.", en: "Join the Amigos do Bairro club. Every coffee counts — earn points, redeem rewards and book your table." },
  "land.register": { pt: "Criar conta grátis", en: "Create free account" },
  "land.member": { pt: "Já sou membro", en: "I'm already a member" },
  "land.memberQ": { pt: "Já tens conta?", en: "Already have an account?" },
  "land.memberLink": { pt: "Entrar", en: "Log in" },
  "land.why": { pt: "Porquê ser membro", en: "Why become a member" },
  "land.f1.t": { pt: "Ganha pontos", en: "Earn points" },
  "land.f1.d": { pt: "Em cada visita acumulas pontos e carimbos.", en: "Earn points and stamps on every visit." },
  "land.f2.t": { pt: "Troca recompensas", en: "Redeem rewards" },
  "land.f2.d": { pt: "Cafés, bolos e descontos só para membros.", en: "Coffees, cakes and members-only discounts." },
  "land.f3.t": { pt: "Reserva mesa", en: "Book a table" },
  "land.f3.d": { pt: "Garante o teu lugar em poucos toques.", en: "Secure your spot in just a few taps." },
  "land.house": { pt: "Da nossa casa", en: "From our kitchen" },
  "land.hours": { pt: "Horário", en: "Hours" },
  "land.hoursVal": { pt: ["Seg–Sex · 09h00–16h00 (Sex tb 18h30–21h00)", "Sáb e Dom · 09h00–14h30"], en: ["Mon–Fri · 9am–4pm (Fri also 6:30–9pm)", "Sat & Sun · 9am–2:30pm"] },
  "land.where": { pt: "Onde", en: "Where" },
  "land.whereVal": { pt: ["R. Dâmaso da Encarnação 53C", "8700-247 Quelfes · Olhão"], en: ["R. Dâmaso da Encarnação 53C", "8700-247 Quelfes · Olhão"] },
  "land.phone": { pt: "Telefone", en: "Phone" },
  "land.phoneVal": { pt: "912 021 759", en: "912 021 759" },
  "land.address": { pt: "Morada", en: "Address" },
  "land.footer": { pt: "Feito com carinho para o Bairro · Fornecido por RedDune Solutions", en: "Made with love for the neighbourhood · Powered by RedDune Solutions" },
  "land.visit": { pt: "Visita-nos", en: "Visit us" },
  "land.openMaps": { pt: "Ver no Google Maps", en: "Open in Google Maps" },

  // Auth
  "auth.regTitle": { pt: "Criar conta", en: "Create account" },
  "auth.loginTitle": { pt: "Bem-vinda de volta", en: "Welcome back" },
  "auth.regSub": { pt: "Junta-te aos Amigos do Bairro", en: "Join the Amigos do Bairro" },
  "auth.loginSub": { pt: "Entra para ver os teus pontos", en: "Sign in to see your points" },
  "auth.tabLogin": { pt: "Entrar", en: "Sign in" },
  "auth.tabReg": { pt: "Registar", en: "Register" },
  "auth.name": { pt: "Nome", en: "Name" },
  "auth.namePh": { pt: "O teu nome", en: "Your name" },
  "auth.email": { pt: "Email", en: "Email" },
  "auth.pass": { pt: "Palavra-passe", en: "Password" },
  "auth.phone": { pt: "Telemóvel", en: "Phone" },
  "auth.forgot": { pt: "Esqueci-me da palavra-passe", en: "Forgot password" },
  "auth.regBtn": { pt: "Criar conta", en: "Create account" },
  "auth.loginBtn": { pt: "Entrar na conta", en: "Sign in" },
  "auth.terms": { pt: "Ao registar aceitas os termos e a política de privacidade dos Amigos do Bairro.", en: "By registering you accept the Amigos do Bairro terms and privacy policy." },
  "auth.or": { pt: "ou continua com", en: "or continue with" },

  // Comum / QR
  "common.lang": { pt: "Idioma", en: "Language" },
  "common.close": { pt: "Fechar", en: "Close" },
  "qr.title": { pt: "O teu cartão", en: "Your card" },
  "qr.sub": { pt: "Mostra ao balcão para somar pontos", en: "Show at the counter to earn points" },

  // Home / MemberCard
  "mc.balance": { pt: "Saldo de pontos", en: "Points balance" },
  "mc.since": { pt: (d: string) => `Membro desde ${d}`, en: (d: string) => `Member since ${d}` },
  "mc.show": { pt: "Mostrar", en: "Show" },
  "home.greet": { pt: "Bom dia,", en: "Good morning," },
  "home.hello": { pt: (n: string) => `Olá, ${n} 👋`, en: (n: string) => `Hi, ${n} 👋` },
  "home.stampCard": { pt: "Cartão de carimbos", en: "Stamp card" },
  "home.q.reserve": { pt: "Reservar", en: "Book" },
  "home.q.menu": { pt: "Ver menu", en: "View menu" },
  "home.q.prizes": { pt: "Prémios", en: "Prizes" },
  "home.q.card": { pt: "Cartão", en: "Card" },
  "home.toGoPre": { pt: "Faltam ", en: "Just " },
  "home.almost": { pt: "Estás quase lá!", en: "You're almost there!" },
  "home.almostSub": { pt: (n: number) => `Mais ${n} pts e desbloqueias uma recompensa.`, en: (n: number) => `${n} more pts to unlock a reward.` },
  "home.prizes": { pt: "Os teus prémios", en: "Your rewards" },
  "home.prizesSub": { pt: "Vê o que podes trocar pelos teus pontos.", en: "See what you can redeem with your points." },
  "home.news": { pt: "Novidades no bairro", en: "Neighbourhood news" },
  "tiers.title": { pt: "Escalões do clube", en: "Club tiers" },
  "tiers.sub": { pt: "Acumula pontos e sobe de escalão para desbloquear mais benefícios.", en: "Earn points and climb the tiers to unlock more perks." },
  "tiers.current": { pt: "Atual", en: "Current" },
  "tiers.from": { pt: (n: number) => `A partir de ${n} pts`, en: (n: number) => `From ${n} pts` },
  "tiers.toNext": { pt: (n: number, t: string) => `Faltam ${n} pts para ${t}`, en: (n: number, t: string) => `${n} pts to reach ${t}` },
  "home.n1.t": { pt: "Pastéis de nata 2x1", en: "Custard tarts 2-for-1" },
  "home.n1.d": { pt: "Todas as quartas, das 16h às 18h.", en: "Every Wednesday, 4pm to 6pm." },
  "home.n2.t": { pt: "Novo Prato do Dia", en: "New Dish of the Day" },
  "home.n2.d": { pt: "Bacalhau à Brás esta semana.", en: "Bacalhau à Brás this week." },

  // LoyaltyCard
  "card.title": { pt: "O meu cartão", en: "My card" },
  "card.pointsCap": { pt: "pontos · 1€ = 1pt", en: "points · €1 = 1pt" },
  "card.stampsCap": { pt: "carimbos · 10 = raspadinhas", en: "stamps · 10 = scratch cards" },
  "card.yourStamps": { pt: "Os teus carimbos", en: "Your stamps" },
  "card.perStamp": { pt: (e: number) => `a cada ${e}€ → 1 carimbo`, en: (e: number) => `every €${e} → 1 stamp` },
  "card.register": { pt: "Registar compra", en: "Log a purchase" },
  "card.registerDemo": { pt: "(demo balcão)", en: "(counter demo)" },
  "card.haveScratch": { pt: (n: number) => `Tens ${n} raspadinha${n > 1 ? "s" : ""}!`, en: (n: number) => `You have ${n} scratch card${n > 1 ? "s" : ""}!` },
  "card.yourScratch": { pt: "As tuas raspadinhas", en: "Your scratch cards" },
  "card.openReveal": { pt: "Abre e descobre o prémio", en: "Open and reveal your prize" },
  "card.collect10": { pt: "Junta 10 carimbos para ganhar", en: "Collect 10 stamps to earn one" },
  "card.history": { pt: "Histórico de pontos", en: "Points history" },
  "card.nextStamp": { pt: "Próximo carimbo", en: "Next stamp" },
  "sheet.register": { pt: "Registar compra", en: "Log a purchase" },
  "sheet.registerSub": { pt: (e: number) => `O balcão regista o valor gasto. A cada ${e}€ soma 1 carimbo.`, en: (e: number) => `The counter logs the amount spent. Every €${e} adds 1 stamp.` },

  // Rewards
  "rew.title": { pt: "Recompensas", en: "Rewards" },
  "rew.intro": { pt: "Troca os teus pontos por mimos da casa. Apresenta o código ao balcão para resgatar.", en: "Swap your points for house treats. Show the code at the counter to redeem." },
  "rew.swap": { pt: "Trocar", en: "Redeem" },
  "rew.need": { pt: "Faltam", en: "Not yet" },

  // Reservas
  "res.title": { pt: "Reservar mesa", en: "Book a table" },
  "res.titleShort": { pt: "Reserva", en: "Booking" },
  "res.booked": { pt: "Mesa reservada!", en: "Table booked!" },
  "res.bookedSub": { pt: "Esperamos por ti no bairro. Enviámos a confirmação por email.", en: "See you in the neighbourhood. We've emailed your confirmation." },
  "res.day": { pt: "Dia", en: "Day" },
  "res.hour": { pt: "Hora", en: "Time" },
  "res.people": { pt: "Pessoas", en: "People" },
  "res.person1": { pt: "pessoa", en: "person" },
  "res.personN": { pt: "pessoas", en: "people" },
  "res.newRes": { pt: "Nova reserva", en: "New booking" },
  "res.next": { pt: "Próxima reserva", en: "Next booking" },
  "res.chooseDay": { pt: "Escolhe o dia", en: "Choose the day" },
  "res.chooseTime": { pt: "A que horas", en: "What time" },
  "res.chooseHowMany": { pt: "Quantas pessoas", en: "How many people" },
  "res.upTo12": { pt: "Mesas até 12 lugares", en: "Tables up to 12 seats" },
  "res.confirm": { pt: (wd: string, t: string) => `Confirmar · ${wd} ${t}`, en: (wd: string, t: string) => `Confirm · ${wd} ${t}` },
  "res.pickHour": { pt: "Escolhe uma hora", en: "Pick a time" },
  "res.statusConfirmed": { pt: "Confirmada", en: "Confirmed" },
  "res.today": { pt: "Hoje", en: "Today" },
  "res.tomorrow": { pt: "Amanhã", en: "Tomorrow" },

  // Menu
  "menu.title": { pt: "Menu", en: "Menu" },
  "menu.pointNote": { pt: ["Cada euro gasto vale ", "1 ponto", " no teu cartão."], en: ["Every euro spent is worth ", "1 point", " on your card."] },

  // Perfil
  "prof.title": { pt: "Perfil", en: "Profile" },
  "prof.stat.points": { pt: "pontos", en: "points" },
  "prof.stat.stamps": { pt: "carimbos", en: "stamps" },
  "prof.stat.visits": { pt: "visitas", en: "visits" },
  "prof.r.edit": { pt: "Editar perfil", en: "Edit profile" },
  "prof.r.notif": { pt: "Notificações", en: "Notifications" },
  "prof.r.notifOn": { pt: "Ativas", en: "On" },
  "prof.r.pay": { pt: "Métodos de pagamento", en: "Payment methods" },
  "prof.r.addr": { pt: "Morada e contactos", en: "Address & contacts" },
  "prof.r.help": { pt: "Ajuda e suporte", en: "Help & support" },
  "prof.admin": { pt: "Painel de administração", en: "Admin panel" },
  "prof.adminSub": { pt: "Gerir prémios, resgates e estatísticas", en: "Manage prizes, redemptions and stats" },
  "prof.logout": { pt: "Terminar sessão", en: "Log out" },

  // Editar perfil
  "edit.title": { pt: "Editar perfil", en: "Edit profile" },
  "edit.photo": { pt: "Alterar foto", en: "Change photo" },
  "edit.section": { pt: "Dados pessoais", en: "Personal details" },
  "edit.name": { pt: "Nome completo", en: "Full name" },
  "edit.namePh": { pt: "O teu nome", en: "Your name" },
  "edit.email": { pt: "Email", en: "Email" },
  "edit.phone": { pt: "Telemóvel", en: "Phone" },
  "edit.birthday": { pt: "Data de nascimento", en: "Date of birth" },
  "edit.member": { pt: "Membro desde", en: "Member since" },
  "edit.save": { pt: "Guardar alterações", en: "Save changes" },
  "edit.saved": { pt: "Perfil atualizado ✓", en: "Profile updated ✓" },

  // Raspadinhas / Prémios
  "sc.special": { pt: "ESPECIAL", en: "SPECIAL" },
  "sc.common": { pt: "COMUM", en: "COMMON" },
  "sc.scratchHere": { pt: "✦  RASPA AQUI  ✦", en: "✦  SCRATCH HERE  ✦" },
  "sc.dragReveal": { pt: "arrasta o dedo para revelar", en: "drag your finger to reveal" },
  "sc.cardLabel": { pt: "RASPADINHA", en: "SCRATCH CARD" },
  "sc.won": { pt: "🎉 Ganhaste!", en: "🎉 You won!" },
  "sc.wonSub": { pt: "Guarda na carteira e mostra ao balcão para usar.", en: "Save it to your wallet and show it at the counter to use." },
  "sc.saveWallet": { pt: "Guardar na carteira", en: "Save to wallet" },
  "sc.hintRaspar": { pt: "Raspa a folha dourada para descobrir o prémio.", en: "Scratch the gold foil to reveal your prize." },
  "sc.noStock": { pt: "Sem stock", en: "Out of stock" },
  "sc.noStockSub": { pt: "Fala com o balcão", en: "Ask at the counter" },
  "pz.title": { pt: "Prémios", en: "Prizes" },
  "pz.bigPrize": { pt: "Prémio grande", en: "Big prize" },
  "pz.houseTreat": { pt: "Mimo da casa", en: "House treat" },
  "pz.scratch": { pt: "Raspar", en: "Scratch" },
  "pz.yourScratch": { pt: "AS TUAS RASPADINHAS", en: "YOUR SCRATCH CARDS" },
  "pz.havePending": { pt: (n: number) => `Tens ${n} raspadinha${n > 1 ? "s" : ""} por abrir!`, en: (n: number) => `You have ${n} scratch card${n > 1 ? "s" : ""} to open!` },
  "pz.noneYet": { pt: "Ainda sem raspadinhas", en: "No scratch cards yet" },
  "pz.eachTen": { pt: "A cada 10 carimbos ganhas 1 especial + 1 comum.", en: "Every 10 stamps earns you 1 special + 1 common." },
  "pz.keepGoing": { pt: "Continua a juntar carimbos — a tua sorte está quase a chegar.", en: "Keep collecting stamps — your luck is almost here." },
  "pz.myWallet": { pt: "A minha carteira", en: "My wallet" },
  "pz.code": { pt: "Código", en: "Code" },
  "pz.used": { pt: "Usado", en: "Used" },
  "pz.toUse": { pt: "Por usar", en: "To use" },
  "pz.walletEmpty": { pt: "Os prémios que ganhares aparecem aqui.", en: "Prizes you win will appear here." },
  "pz.swapPoints": { pt: "Trocar pontos por mimos", en: "Swap points for treats" },

  // Celebração
  "win.full": { pt: "Cartola completa! 🎉", en: "Card complete! 🎉" },
  "win.open": { pt: "Abrir raspadinhas", en: "Open scratch cards" },

  // Toasts
  "toast.redeem": { pt: (n: string) => `Resgataste: ${n} 🎉`, en: (n: string) => `Redeemed: ${n} 🎉` },
  "toast.stamps": { pt: (a: number, n: number) => `+${a}€ · ${n} carimbo${n > 1 ? "s" : ""} ✓`, en: (a: number, n: number) => `+€${a} · ${n} stamp${n > 1 ? "s" : ""} ✓` },
  "toast.spend": { pt: (a: number) => `+${a}€ registados`, en: (a: number) => `+€${a} recorded` },
  "toast.prizeSaved": { pt: "Prémio guardado na carteira ✓", en: "Prize saved to wallet ✓" },
  "toast.redeemOk": { pt: "Resgate validado ✓", en: "Redemption validated ✓" },
  "toast.bookingOk": { pt: "Reserva confirmada ✓", en: "Booking confirmed ✓" },
};
